name: Build hns
on:
  schedule:
    - cron:  '20 14 * * 4'
  push:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Get code coverage
      run: cargo install cargo-tarpaulin && cargo tarpaulin
    - name: Run `help` command for sanity
      run: cargo run --verbose -- --help
